psensor: add cpp supporting
mangOH/legatoDataHub pull request #4
Opened 2019-11-20 09:21 UTC by nxthongbk

Grove Sensor reading file is written by cpp need to integrate with datahub/psensor to create  object.

2019-11-21 19:01 UTC, dpfrey requested changes
The change itself looks good, but I think the commit message could be improved.  I think commit messages should be within the scope of the repository. Grove sensors and the broader mangOH ecosystem is not within the scope of the data hub.  I would prefer a message like this:
```
psensor: add C++ support                                                                                                                                                                                                                                                         
                                                                         
Add extern "C" to periodicSensor.h so that the periodicSensor component  
can be used by components written in C++.
```

2019-11-21 19:14 UTC, jtchitty commented
> The change itself looks good, but I think the commit message could be improved. I think commit messages should be within the scope of the repository. Grove sensors and the broader mangOH ecosystem is not within the scope of the data hub. I would prefer a message like this:
> 
> ```
> psensor: add C++ support                                                                                                                                                                                                                                                         
>                                                                          
> Add extern "C" to periodicSensor.h so that the periodicSensor component  
> can be used by components written in C++.
> ```

Agreed.

2019-11-22 06:44 UTC, nxthongbk commented
Hi David and Jen

I updated commit message. Please help me to review.

Thanks
Thong Nguyen

2019-11-22 16:09 UTC, dpfrey approved these changes

2019-11-22 16:13 UTC, merged